"""dict table

Revision ID: 554897065891
Revises: eae887d5104d
Create Date: 2025-01-12 11:30:54.324678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554897065891'
down_revision = 'eae887d5104d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_spanish', sa.String(length=64), nullable=True),
    sa.Column('word_german', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_word_german'), ['word_german'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_word_spanish'), ['word_spanish'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word_spanish'))
        batch_op.drop_index(batch_op.f('ix_words_word_german'))

    op.drop_table('words')
    # ### end Alembic commands ###
