"""new database runs

Revision ID: 804e2bb0dc3e
Revises: 
Create Date: 2024-09-15 18:34:15.577863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804e2bb0dc3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kilometers', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    # ### end Alembic commands ###
